# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'LYPhotoBrowserDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'SGInfiniteView', '0.1.2'
pod 'SDWebImage', '4.2.2'
pod 'Masonry', '1.1.0'

  # Pods for LYPhotoBrowserDemo
pod 'SVProgressHUD'

end
