# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'LYPhotoBrowserDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'SGInfiniteView'
pod 'SDWebImage'
pod 'Masonry'
pod 'DACircularProgress'
  # Pods for LYPhotoBrowserDemo

end
